// Plain-text / Markdown versions of the portfolio for LLMs and AI search
// (https://llmstxt.org). Generated at build time from lib/site.ts.
import { absolute, awards, education, experience, papers, plain, profile, projects, skills } from './site';

const facts = () => [
  `- Name: ${profile.name}`,
  `- Role: ${profile.role} at ${profile.company}`,
  `- Location: ${profile.location}, USA`,
  `- Experience: 3+ years of professional software engineering across Android, web and AI`,
  `- Education: ${education.map((e) => `${e.degree}, ${e.school} (${e.dates}${e.note ? `, ${e.note}` : ''})`).join('; ')}`,
  `- Core stack: Kotlin, Jetpack Compose, React Native, React, Next.js, TypeScript, PostgreSQL/Supabase, Firebase, Gemini API`,
  `- Open to: full-stack, mobile and AI engineering roles`,
  `- Contact: ${profile.email} · ${profile.linkedin} · ${profile.github}`,
];

export function llmsTxt() {
  return [
    `# ${profile.name}`,
    '',
    `> ${profile.summary}`,
    '',
    ...facts(),
    '',
    '## Profile',
    '',
    `- [Portfolio](${absolute('/')}): experience, projects, research papers, skills and contact details`,
    `- [Structured profile JSON](${absolute('/profile.json')}): complete machine-readable profile`,
    `- [About](${absolute('/about')}): profile, skills, education, awards and contact details`,
    `- [Experience](${absolute('/experience')}): detailed professional work history`,
    `- [Research](${absolute('/research')}): papers, abstracts and PDF links`,
    `- [Full profile in Markdown](${absolute('/llms-full.txt')}): everything on the portfolio as plain text, for AI assistants`,
    `- [Resume (PDF)](${absolute(profile.resume)}): one-page resume`,
    `- [GitHub](${profile.github}): source code and side projects`,
    `- [LinkedIn](${profile.linkedin}): professional profile`,
    '',
    '## Experience',
    '',
    ...experience.map((j) => `- ${j.role}, ${j.company} (${j.dates}): ${plain(j.points[0])}`),
    '',
    '## Projects',
    '',
    ...projects.map((p) => `- [${p.name}](${absolute(`/projects/${p.slug}`)}): ${p.pitch} Stack: ${p.tags.join(', ')}.`),
    '',
    '## Research',
    '',
    ...papers.map((p) => `- [${p.title}](${absolute(p.file)}): ${p.badge}, ${p.venue}, ${p.year}.${p.result ? ` ${p.result.value} ${p.result.label}.` : ''}`),
    '',
  ].join('\n');
}

export function llmsFullTxt() {
  return [
    `# ${profile.name}: ${profile.role}`,
    '',
    `> ${profile.summary}`,
    '',
    ...facts(),
    `- Portfolio: ${absolute('/')}`,
    `- Structured profile JSON: ${absolute('/profile.json')}`,
    `- About: ${absolute('/about')}`,
    `- Experience: ${absolute('/experience')}`,
    `- Research: ${absolute('/research')}`,
    `- Resume: ${absolute(profile.resume)}`,
    '',
    '## Contact',
    '',
    `- Email: ${profile.email}`,
    `- LinkedIn: ${profile.linkedin}`,
    `- GitHub: ${profile.github}`,
    '',
    '## Experience',
    '',
    ...experience.flatMap((j) => [
      `### ${j.role}, ${j.company}`,
      '',
      `${j.dates}`,
      '',
      ...j.points.map((p) => `- ${plain(p)}`),
      '',
      `Technologies: ${j.tags.join(', ')}`,
      '',
    ]),
    '## Projects',
    '',
    ...projects.flatMap((p) => [
      `### ${p.name} (${p.kind})`,
      '',
      `${p.dates}`,
      '',
      p.pitch,
      `Page: ${absolute(`/projects/${p.slug}`)}`,
      '',
      ...p.points.map((pt) => `- ${plain(pt)}`),
      '',
      `Technologies: ${p.tags.join(', ')}`,
      '',
    ]),
    '## Research and writing',
    '',
    ...papers.flatMap((p) => [
      `### ${p.title}`,
      '',
      `${p.badge} · ${p.venue} · ${p.year}${p.coAuthored ? ' · co-authored' : ''}`,
      '',
      ...(p.result ? [`Key result: ${p.result.value} ${p.result.label}.`, ''] : []),
      `Abstract: ${p.abstract}`,
      '',
      `Topics: ${p.tags.join(', ')}`,
      '',
      `PDF: ${absolute(p.file)}`,
      '',
    ]),
    '## Skills',
    '',
    ...skills.map((s) => `- ${s.group}: ${s.items.join(', ')}`),
    '',
    '## Education',
    '',
    ...education.map((e) => `- ${e.degree}, ${e.school}, ${e.place} (${e.dates})${e.note ? `, ${e.note}` : ''}`),
    '',
    '## Awards and certificates',
    '',
    ...awards.map((a) => `- ${a}`),
    '',
  ].join('\n');
}
